from enum import Enum

class SessionStatus(Enum):
    STATUS_AGREEMENT = 'AGREEMENT'
    STATUS_CREATED = 'CREATED'
    STATUS_ASKING_FOR_PLACE = 'ASKING_FOR_PLACE'
    STATUS_CHOOSING_PLACE = 'CHOOSING_PLACE'
    STATUS_ASKING_FOR_COMMENT = 'ASKING_FOR_COMMENT'
    STATUS_REQUESTING_SERVICE = 'REQUESTING_SERVICE'
    STATUS_SERVICE_IN_PROGRESS = 'SERVICE_IN_PROGRESS'
    STATUS_COMPLETED = 'COMPLETED'
    STATUS_ASKING_FOR_NAME = 'ASKING_FOR_NAME'